services:
  db:
    image: timescale/timescaledb:latest-pg18
    container_name: timescaledb
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      PGDATA: /pgdata/data
      POSTGRES_DB: tsdb
      POSTGRES_USER: tsadmin
      POSTGRES_PASSWORD: strongpassword123
    volumes:
      - timescaledb_data:/pgdata

volumes:
  timescaledb_data:
    name: timescaledb_data