"""init

Revision ID: d141d73b1e5e
Revises: 
Create Date: 2026-06-26 11:55:31.599426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd141d73b1e5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capteur', sa.String(), nullable=True),
    sa.Column('valeur', sa.Float(), nullable=True),
    sa.Column('horodatage', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mesures')
    # ### end Alembic commands ###
